datamodule:
  _target_: regression.DataModule
  batch_size: 1024
  num_workers: 4
  val_split: 0.2
model:
  _target_: regression.LitModel
  input_dim: 2048
  hidden_dim: 1024
  num_layers: 8
  output_dim: 1
  lr: 0.001
  use_bn: true
  dropout: 0.5
seed: 42
trainer:
  max_epochs: 10000
  accelerator: gpu
  devices: 2
  strategy: ddp
  logger: true
  callbacks:
  - monitor: val_p_s
    patience: 100
    mode: max
    _target_: pytorch_lightning.callbacks.EarlyStopping
